### ISSUE TITLE
Improve the performance and UX of the `predict_xgb` function 

### ISSUE THREAD

**Issue by mesejo** [xorq-labs/xorq#2]
#### Description
The current implementation of the `predict_xgb` function in the LetSQL could benefit from several enhancements to improve its performance and ease of use. 

#### Tasks
- [ ] Optimize the `predict` function to intelligently expand the star (`*`) for only the necessary columns. This speeds up the `predict_xgb` function by reducing data transfer and processing and makes it easier to use by eliminating manual column writing.
- [ ] Simplify function usage by removing objective function specifications. Inferring the objective function streamlines the `predict_xgb` function and enhances user-friendliness.
- [ ] Update the model loading process to load an XGBoost model instead of a gdbt-rs transformation, eliminating manual model transformation.

**Version:** 0.1.2
